/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BatchAdditionDialog: typeof import('./components/batch/BatchAdditionDialog.vue')['default']
    BatchAdditionsTab: typeof import('./components/batch/BatchAdditionsTab.vue')['default']
    BatchBrewSessionDialog: typeof import('./components/batch/BatchBrewSessionDialog.vue')['default']
    BatchBrewSessionsTab: typeof import('./components/batch/BatchBrewSessionsTab.vue')['default']
    BatchDeleteDialog: typeof import('./components/batch/BatchDeleteDialog.vue')['default']
    BatchDetails: typeof import('./components/BatchDetails.vue')['default']
    BatchEditDialog: typeof import('./components/batch/BatchEditDialog.vue')['default']
    BatchFlowTab: typeof import('./components/batch/BatchFlowTab.vue')['default']
    BatchHotSideAdditionDialog: typeof import('./components/batch/BatchHotSideAdditionDialog.vue')['default']
    BatchHotSideMeasurementDialog: typeof import('./components/batch/BatchHotSideMeasurementDialog.vue')['default']
    BatchList: typeof import('./components/BatchList.vue')['default']
    BatchMeasurementDialog: typeof import('./components/batch/BatchMeasurementDialog.vue')['default']
    BatchMeasurementsTab: typeof import('./components/batch/BatchMeasurementsTab.vue')['default']
    BatchSparklineCard: typeof import('./components/batch/BatchSparklineCard.vue')['default']
    BatchSummaryTab: typeof import('./components/batch/BatchSummaryTab.vue')['default']
    BatchTimelineExtendedDialog: typeof import('./components/batch/BatchTimelineExtendedDialog.vue')['default']
    BatchTimelineTab: typeof import('./components/batch/BatchTimelineTab.vue')['default']
    BatchVolumeDialog: typeof import('./components/batch/BatchVolumeDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RecipeDeleteDialog: typeof import('./components/recipe/RecipeDeleteDialog.vue')['default']
    RecipeDetails: typeof import('./components/recipe/RecipeDetails.vue')['default']
    RecipeEditDialog: typeof import('./components/recipe/RecipeEditDialog.vue')['default']
    RecipeFermentablesTab: typeof import('./components/recipe/RecipeFermentablesTab.vue')['default']
    RecipeHopsTab: typeof import('./components/recipe/RecipeHopsTab.vue')['default']
    RecipeIngredientDialog: typeof import('./components/recipe/RecipeIngredientDialog.vue')['default']
    RecipeOverviewTab: typeof import('./components/recipe/RecipeOverviewTab.vue')['default']
    RecipeSpecsTab: typeof import('./components/recipe/RecipeSpecsTab.vue')['default']
    RecipeYeastTab: typeof import('./components/recipe/RecipeYeastTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SankeyDiagram: typeof import('./components/SankeyDiagram.vue')['default']
    VesselDetails: typeof import('./components/VesselDetails.vue')['default']
    VesselEditDialog: typeof import('./components/vessel/VesselEditDialog.vue')['default']
    VesselList: typeof import('./components/VesselList.vue')['default']
  }
}
