/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BatchAdditionDialog: typeof import('./components/batch/BatchAdditionDialog.vue')['default']
    BatchAdditionsTab: typeof import('./components/batch/BatchAdditionsTab.vue')['default']
    BatchAssignFermenterDialog: typeof import('./components/batch/BatchAssignFermenterDialog.vue')['default']
    BatchBrewDayTab: typeof import('./components/batch/BatchBrewDayTab.vue')['default']
    BatchBrewSessionDialog: typeof import('./components/batch/BatchBrewSessionDialog.vue')['default']
    BatchBrewSessionsTab: typeof import('./components/batch/BatchBrewSessionsTab.vue')['default']
    BatchCreateDialog: typeof import('./components/batch/BatchCreateDialog.vue')['default']
    BatchDeleteDialog: typeof import('./components/batch/BatchDeleteDialog.vue')['default']
    BatchDetails: typeof import('./components/BatchDetails.vue')['default']
    BatchEditDialog: typeof import('./components/batch/BatchEditDialog.vue')['default']
    BatchFlowTab: typeof import('./components/batch/BatchFlowTab.vue')['default']
    BatchHotSideAdditionDialog: typeof import('./components/batch/BatchHotSideAdditionDialog.vue')['default']
    BatchHotSideMeasurementDialog: typeof import('./components/batch/BatchHotSideMeasurementDialog.vue')['default']
    BatchList: typeof import('./components/BatchList.vue')['default']
    BatchMarkEmptyDialog: typeof import('./components/batch/BatchMarkEmptyDialog.vue')['default']
    BatchMeasurementDialog: typeof import('./components/batch/BatchMeasurementDialog.vue')['default']
    BatchMeasurementsTab: typeof import('./components/batch/BatchMeasurementsTab.vue')['default']
    BatchSparklineCard: typeof import('./components/batch/BatchSparklineCard.vue')['default']
    BatchSummaryTab: typeof import('./components/batch/BatchSummaryTab.vue')['default']
    BatchTimelineExtendedDialog: typeof import('./components/batch/BatchTimelineExtendedDialog.vue')['default']
    BatchTimelineTab: typeof import('./components/batch/BatchTimelineTab.vue')['default']
    BatchVolumeDialog: typeof import('./components/batch/BatchVolumeDialog.vue')['default']
    LineDetailForm: typeof import('./components/procurement/LineDetailForm.vue')['default']
    PurchaseOrderFeeDialog: typeof import('./components/procurement/PurchaseOrderFeeDialog.vue')['default']
    PurchaseOrderFeeList: typeof import('./components/procurement/PurchaseOrderFeeList.vue')['default']
    PurchaseOrderHeader: typeof import('./components/procurement/PurchaseOrderHeader.vue')['default']
    PurchaseOrderLineDialog: typeof import('./components/procurement/PurchaseOrderLineDialog.vue')['default']
    PurchaseOrderLineList: typeof import('./components/procurement/PurchaseOrderLineList.vue')['default']
    PurchaseOrderStatusMenu: typeof import('./components/procurement/PurchaseOrderStatusMenu.vue')['default']
    ReceiveShipmentStep1: typeof import('./components/procurement/ReceiveShipmentStep1.vue')['default']
    ReceiveShipmentStep2: typeof import('./components/procurement/ReceiveShipmentStep2.vue')['default']
    ReceiveShipmentStep3: typeof import('./components/procurement/ReceiveShipmentStep3.vue')['default']
    ReceiveShipmentWizard: typeof import('./components/procurement/ReceiveShipmentWizard.vue')['default']
    ReceiveWithoutPODialog: typeof import('./components/procurement/ReceiveWithoutPODialog.vue')['default']
    RecipeDeleteDialog: typeof import('./components/recipe/RecipeDeleteDialog.vue')['default']
    RecipeDetails: typeof import('./components/recipe/RecipeDetails.vue')['default']
    RecipeEditDialog: typeof import('./components/recipe/RecipeEditDialog.vue')['default']
    RecipeFermentablesTab: typeof import('./components/recipe/RecipeFermentablesTab.vue')['default']
    RecipeHopsTab: typeof import('./components/recipe/RecipeHopsTab.vue')['default']
    RecipeIngredientDialog: typeof import('./components/recipe/RecipeIngredientDialog.vue')['default']
    RecipeOverviewTab: typeof import('./components/recipe/RecipeOverviewTab.vue')['default']
    RecipeSpecsTab: typeof import('./components/recipe/RecipeSpecsTab.vue')['default']
    RecipeYeastTab: typeof import('./components/recipe/RecipeYeastTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SankeyDiagram: typeof import('./components/SankeyDiagram.vue')['default']
    StockLevelTable: typeof import('./components/inventory/StockLevelTable.vue')['default']
    VesselDetails: typeof import('./components/VesselDetails.vue')['default']
    VesselEditDialog: typeof import('./components/vessel/VesselEditDialog.vue')['default']
    VesselList: typeof import('./components/VesselList.vue')['default']
  }
}
