/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/batches/': RouteRecordInfo<'/batches/', '/batches', Record<never, never>, Record<never, never>>,
    '/batches/[uuid]/': RouteRecordInfo<'/batches/[uuid]/', '/batches/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/batches/all': RouteRecordInfo<'/batches/all', '/batches/all', Record<never, never>, Record<never, never>>,
    '/fermentation': RouteRecordInfo<'/fermentation', '/fermentation', Record<never, never>, Record<never, never>>,
    '/inventory/activity': RouteRecordInfo<'/inventory/activity', '/inventory/activity', Record<never, never>, Record<never, never>>,
    '/inventory/adjustments-transfers': RouteRecordInfo<'/inventory/adjustments-transfers', '/inventory/adjustments-transfers', Record<never, never>, Record<never, never>>,
    '/inventory/ingredients': RouteRecordInfo<'/inventory/ingredients', '/inventory/ingredients', Record<never, never>, Record<never, never>>,
    '/inventory/locations': RouteRecordInfo<'/inventory/locations', '/inventory/locations', Record<never, never>, Record<never, never>>,
    '/inventory/lot-details': RouteRecordInfo<'/inventory/lot-details', '/inventory/lot-details', Record<never, never>, Record<never, never>>,
    '/inventory/product': RouteRecordInfo<'/inventory/product', '/inventory/product', Record<never, never>, Record<never, never>>,
    '/inventory/removals': RouteRecordInfo<'/inventory/removals', '/inventory/removals', Record<never, never>, Record<never, never>>,
    '/inventory/stock-levels': RouteRecordInfo<'/inventory/stock-levels', '/inventory/stock-levels', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/procurement/': RouteRecordInfo<'/procurement/', '/procurement', Record<never, never>, Record<never, never>>,
    '/procurement/purchase-order-fees': RouteRecordInfo<'/procurement/purchase-order-fees', '/procurement/purchase-order-fees', Record<never, never>, Record<never, never>>,
    '/procurement/purchase-order-lines': RouteRecordInfo<'/procurement/purchase-order-lines', '/procurement/purchase-order-lines', Record<never, never>, Record<never, never>>,
    '/procurement/purchase-orders/': RouteRecordInfo<'/procurement/purchase-orders/', '/procurement/purchase-orders', Record<never, never>, Record<never, never>>,
    '/procurement/purchase-orders/[uuid]': RouteRecordInfo<'/procurement/purchase-orders/[uuid]', '/procurement/purchase-orders/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/procurement/suppliers': RouteRecordInfo<'/procurement/suppliers', '/procurement/suppliers', Record<never, never>, Record<never, never>>,
    '/production/': RouteRecordInfo<'/production/', '/production', Record<never, never>, Record<never, never>>,
    '/production/recipes/': RouteRecordInfo<'/production/recipes/', '/production/recipes', Record<never, never>, Record<never, never>>,
    '/production/recipes/[uuid]/': RouteRecordInfo<'/production/recipes/[uuid]/', '/production/recipes/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/vessels/': RouteRecordInfo<'/vessels/', '/vessels', Record<never, never>, Record<never, never>>,
    '/vessels/[uuid]/': RouteRecordInfo<'/vessels/[uuid]/', '/vessels/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    '/vessels/active': RouteRecordInfo<'/vessels/active', '/vessels/active', Record<never, never>, Record<never, never>>,
    '/vessels/all': RouteRecordInfo<'/vessels/all', '/vessels/all', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/batches/index.vue': {
      routes: '/batches/'
      views: never
    }
    'src/pages/batches/[uuid]/index.vue': {
      routes: '/batches/[uuid]/'
      views: never
    }
    'src/pages/batches/all.vue': {
      routes: '/batches/all'
      views: never
    }
    'src/pages/fermentation.vue': {
      routes: '/fermentation'
      views: never
    }
    'src/pages/inventory/activity.vue': {
      routes: '/inventory/activity'
      views: never
    }
    'src/pages/inventory/adjustments-transfers.vue': {
      routes: '/inventory/adjustments-transfers'
      views: never
    }
    'src/pages/inventory/ingredients.vue': {
      routes: '/inventory/ingredients'
      views: never
    }
    'src/pages/inventory/locations.vue': {
      routes: '/inventory/locations'
      views: never
    }
    'src/pages/inventory/lot-details.vue': {
      routes: '/inventory/lot-details'
      views: never
    }
    'src/pages/inventory/product.vue': {
      routes: '/inventory/product'
      views: never
    }
    'src/pages/inventory/removals.vue': {
      routes: '/inventory/removals'
      views: never
    }
    'src/pages/inventory/stock-levels.vue': {
      routes: '/inventory/stock-levels'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/procurement/index.vue': {
      routes: '/procurement/'
      views: never
    }
    'src/pages/procurement/purchase-order-fees.vue': {
      routes: '/procurement/purchase-order-fees'
      views: never
    }
    'src/pages/procurement/purchase-order-lines.vue': {
      routes: '/procurement/purchase-order-lines'
      views: never
    }
    'src/pages/procurement/purchase-orders/index.vue': {
      routes: '/procurement/purchase-orders/'
      views: never
    }
    'src/pages/procurement/purchase-orders/[uuid].vue': {
      routes: '/procurement/purchase-orders/[uuid]'
      views: never
    }
    'src/pages/procurement/suppliers.vue': {
      routes: '/procurement/suppliers'
      views: never
    }
    'src/pages/production/index.vue': {
      routes: '/production/'
      views: never
    }
    'src/pages/production/recipes/index.vue': {
      routes: '/production/recipes/'
      views: never
    }
    'src/pages/production/recipes/[uuid]/index.vue': {
      routes: '/production/recipes/[uuid]/'
      views: never
    }
    'src/pages/settings.vue': {
      routes: '/settings'
      views: never
    }
    'src/pages/vessels/index.vue': {
      routes: '/vessels/'
      views: never
    }
    'src/pages/vessels/[uuid]/index.vue': {
      routes: '/vessels/[uuid]/'
      views: never
    }
    'src/pages/vessels/active.vue': {
      routes: '/vessels/active'
      views: never
    }
    'src/pages/vessels/all.vue': {
      routes: '/vessels/all'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
