/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/additions': RouteRecordInfo<'/additions', '/additions', Record<never, never>, Record<never, never>>,
    '/batches': RouteRecordInfo<'/batches', '/batches', Record<never, never>, Record<never, never>>,
    '/inventory/': RouteRecordInfo<'/inventory/', '/inventory', Record<never, never>, Record<never, never>>,
    '/inventory/adjustments': RouteRecordInfo<'/inventory/adjustments', '/inventory/adjustments', Record<never, never>, Record<never, never>>,
    '/inventory/beer-lots': RouteRecordInfo<'/inventory/beer-lots', '/inventory/beer-lots', Record<never, never>, Record<never, never>>,
    '/inventory/ingredient-details': RouteRecordInfo<'/inventory/ingredient-details', '/inventory/ingredient-details', Record<never, never>, Record<never, never>>,
    '/inventory/ingredients': RouteRecordInfo<'/inventory/ingredients', '/inventory/ingredients', Record<never, never>, Record<never, never>>,
    '/inventory/locations': RouteRecordInfo<'/inventory/locations', '/inventory/locations', Record<never, never>, Record<never, never>>,
    '/inventory/lot-details': RouteRecordInfo<'/inventory/lot-details', '/inventory/lot-details', Record<never, never>, Record<never, never>>,
    '/inventory/lots': RouteRecordInfo<'/inventory/lots', '/inventory/lots', Record<never, never>, Record<never, never>>,
    '/inventory/movements': RouteRecordInfo<'/inventory/movements', '/inventory/movements', Record<never, never>, Record<never, never>>,
    '/inventory/receipts': RouteRecordInfo<'/inventory/receipts', '/inventory/receipts', Record<never, never>, Record<never, never>>,
    '/inventory/transfers': RouteRecordInfo<'/inventory/transfers', '/inventory/transfers', Record<never, never>, Record<never, never>>,
    '/inventory/usage': RouteRecordInfo<'/inventory/usage', '/inventory/usage', Record<never, never>, Record<never, never>>,
    '/measurements': RouteRecordInfo<'/measurements', '/measurements', Record<never, never>, Record<never, never>>,
    '/procurement/': RouteRecordInfo<'/procurement/', '/procurement', Record<never, never>, Record<never, never>>,
    '/procurement/purchase-order-fees': RouteRecordInfo<'/procurement/purchase-order-fees', '/procurement/purchase-order-fees', Record<never, never>, Record<never, never>>,
    '/procurement/purchase-order-lines': RouteRecordInfo<'/procurement/purchase-order-lines', '/procurement/purchase-order-lines', Record<never, never>, Record<never, never>>,
    '/procurement/purchase-orders': RouteRecordInfo<'/procurement/purchase-orders', '/procurement/purchase-orders', Record<never, never>, Record<never, never>>,
    '/procurement/suppliers': RouteRecordInfo<'/procurement/suppliers', '/procurement/suppliers', Record<never, never>, Record<never, never>>,
    '/reports': RouteRecordInfo<'/reports', '/reports', Record<never, never>, Record<never, never>>,
    '/transfers': RouteRecordInfo<'/transfers', '/transfers', Record<never, never>, Record<never, never>>,
    '/vessels': RouteRecordInfo<'/vessels', '/vessels', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/additions.vue': {
      routes: '/additions'
      views: never
    }
    'src/pages/batches.vue': {
      routes: '/batches'
      views: never
    }
    'src/pages/inventory/index.vue': {
      routes: '/inventory/'
      views: never
    }
    'src/pages/inventory/adjustments.vue': {
      routes: '/inventory/adjustments'
      views: never
    }
    'src/pages/inventory/beer-lots.vue': {
      routes: '/inventory/beer-lots'
      views: never
    }
    'src/pages/inventory/ingredient-details.vue': {
      routes: '/inventory/ingredient-details'
      views: never
    }
    'src/pages/inventory/ingredients.vue': {
      routes: '/inventory/ingredients'
      views: never
    }
    'src/pages/inventory/locations.vue': {
      routes: '/inventory/locations'
      views: never
    }
    'src/pages/inventory/lot-details.vue': {
      routes: '/inventory/lot-details'
      views: never
    }
    'src/pages/inventory/lots.vue': {
      routes: '/inventory/lots'
      views: never
    }
    'src/pages/inventory/movements.vue': {
      routes: '/inventory/movements'
      views: never
    }
    'src/pages/inventory/receipts.vue': {
      routes: '/inventory/receipts'
      views: never
    }
    'src/pages/inventory/transfers.vue': {
      routes: '/inventory/transfers'
      views: never
    }
    'src/pages/inventory/usage.vue': {
      routes: '/inventory/usage'
      views: never
    }
    'src/pages/measurements.vue': {
      routes: '/measurements'
      views: never
    }
    'src/pages/procurement/index.vue': {
      routes: '/procurement/'
      views: never
    }
    'src/pages/procurement/purchase-order-fees.vue': {
      routes: '/procurement/purchase-order-fees'
      views: never
    }
    'src/pages/procurement/purchase-order-lines.vue': {
      routes: '/procurement/purchase-order-lines'
      views: never
    }
    'src/pages/procurement/purchase-orders.vue': {
      routes: '/procurement/purchase-orders'
      views: never
    }
    'src/pages/procurement/suppliers.vue': {
      routes: '/procurement/suppliers'
      views: never
    }
    'src/pages/reports.vue': {
      routes: '/reports'
      views: never
    }
    'src/pages/transfers.vue': {
      routes: '/transfers'
      views: never
    }
    'src/pages/vessels.vue': {
      routes: '/vessels'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
