/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/additions': RouteRecordInfo<'/additions', '/additions', Record<never, never>, Record<never, never>>,
    '/batches': RouteRecordInfo<'/batches', '/batches', Record<never, never>, Record<never, never>>,
    '/measurements': RouteRecordInfo<'/measurements', '/measurements', Record<never, never>, Record<never, never>>,
    '/reports': RouteRecordInfo<'/reports', '/reports', Record<never, never>, Record<never, never>>,
    '/transfers': RouteRecordInfo<'/transfers', '/transfers', Record<never, never>, Record<never, never>>,
    '/vessels': RouteRecordInfo<'/vessels', '/vessels', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/additions.vue': {
      routes: '/additions'
      views: never
    }
    'src/pages/batches.vue': {
      routes: '/batches'
      views: never
    }
    'src/pages/measurements.vue': {
      routes: '/measurements'
      views: never
    }
    'src/pages/reports.vue': {
      routes: '/reports'
      views: never
    }
    'src/pages/transfers.vue': {
      routes: '/transfers'
      views: never
    }
    'src/pages/vessels.vue': {
      routes: '/vessels'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
