DROP TABLE IF EXISTS beer CASCADE;
DROP TABLE IF EXISTS wort CASCADE;
DROP TABLE IF EXISTS batch CASCADE;
DROP TABLE IF EXISTS transfer CASCADE;
DROP TABLE IF EXISTS occupancy CASCADE;
DROP TABLE IF EXISTS volume CASCADE;
